typedef unsigned long long uint64_t;
typedef unsigned int uint;
typedef unsigned long size_t;
#define STDIN_FD 0
#define STDOUT_FD 1
const char *source = "typedef unsigned long long uint64_t;\n"
"typedef unsigned int uint;\n"
"typedef unsigned long size_t;\n"
"#define STDIN_FD 0\n"
"#define STDOUT_FD 1\n"
"const char *source = \"@\";\n"
"__attribute__((naked)) void _start(void) {__asm__ volatile (\"mov $0, %rdi\\nmov $0, %rsi\\ncall main\\nmov %eax, %edi\\nmov $231, %rax\\nsyscall\");}\n"
"static int sys_write(int fd, const void *buf, unsigned int count) {int ret;__asm__ volatile (\"mov $1, %%rax\\nmov %1, %%rdi\\nmov %2, %%rsi\\nmov %3, %%rdx\\nsyscall\\nmov %%eax, %0\\n\": \"=r\"(ret): \"r\"((uint64_t)fd), \"r\"(buf), \"r\"((uint64_t)count): \"rax\", \"rdi\", \"rsi\", \"rdx\");return ret;}\n"
"static int sys_read(int fd, void *buf, unsigned int count) {int ret;__asm__ volatile (\"mov $0, %%rax\\nmov %1, %%rdi\\nmov %2, %%rsi\\nmov %3, %%rdx\\nsyscall\\nmov %%eax, %0\\n\": \"=r\"(ret): \"r\"((uint64_t)fd), \"r\"(buf), \"r\"((uint64_t)count): \"rax\", \"rdi\", \"rsi\", \"rdx\");return ret;}\n"
"int putchar(int c) {char ch = (char)c;if (sys_write(STDOUT_FD, &ch, 1) != 1) return -1;return c;}\n"
"int fputs(const char *s) {size_t len = 0;while (s[len]) len++;int written = sys_write(STDOUT_FD, s, (unsigned int)len);return (written == (int)len) ? (int)len : -1;}\n"
"int puts(const char *s) {if (fputs(s) < 0) return -1;if (putchar('\\n') < 0) return -1;return 1;}\n"
"size_t strlen(const char *s) {size_t len = 0;while (s[len]) len++;return len;}\n"
"int strncmp(const char *a, const char *b, size_t n) {size_t i = 0;for (; i < n; i++) {unsigned char ca = (unsigned char)a[i];unsigned char cb = (unsigned char)b[i];if (ca != cb) return (int)(ca - cb);if (ca == 0) return 0;}return 0;}\n"
"size_t strcspn(const char *s, const char *reject) {size_t i = 0;for (; s[i]; i++) {size_t j = 0;while (reject[j]) {if (s[i] == reject[j]) return i;j++;}}return i;}\n"
"int atoi(const char *s) {int sign = 1;int val = 0;while (*s == ' ' || *s == '\\t' || *s == '\\n') s++;if (*s == '-') { sign = -1; s++; }else if (*s == '+') s++;while (*s >= '0' && *s <= '9') {val = val * 10 + (*s - '0');s++;}return sign * val;}\n"
"int fgets(char *buf, int maxlen) {int i = 0;while (i < maxlen - 1) {char c;int r = sys_read(STDIN_FD, &c, 1);if (r <= 0) break;buf[i++] = c;if (c == '\\n') break;}if (i == 0) return 0;buf[i] = '\\0';return 1;}\n"
"int printf(const char *fmt, int val) {int count = 0;while (*fmt) {if (*fmt == '%') {fmt++;if (*fmt == '%') {if (putchar('%') < 0) return -1;count++;} else if (*fmt == 'd') {char buf[20];int i = 0;unsigned int uval;int negative = 0;if (val == 0) {buf[i++] = '0';} else {if (val < 0) {negative = 1;uval = (unsigned int)(-val);} else {uval = (unsigned int)val;}while (uval) {buf[i++] = '0' + (uval % 10);uval /= 10;}if (negative) buf[i++] = '-';}for (int j = i - 1; j >= 0; j--) {if (putchar(buf[j]) < 0) return -1;count++;}} else {if (putchar('%') < 0) return -1;if (putchar(*fmt) < 0) return -1;count += 2;}fmt++;} else {if (putchar(*fmt) < 0) return -1;count++;fmt++;}}return count;}\n"
"void print(const char *src) {static const char hex[] = \"0123456789abcdef\";unsigned char c;while ((c = (unsigned char)*src++)) {if (c == '\\\\') fputs(\"\\\\\\\\\");else if (c == '\"') fputs(\"\\\\\\\"\");else if (c == '\\n') fputs(\"\\\\n\\\"\\n\\\"\");else if (c == '\\t') fputs(\"\\\\t\");else if (c >= 32 && c < 127) putchar(c);else {putchar('\\\\');putchar('x');putchar(hex[c >> 4]);putchar(hex[c & 0xF]);}}}\n"
"void is_prime(const char *cn) {int n = atoi(cn);if (n <= 1) {puts(\"False\");return;}for (int i = 2; i * i <= n; i++) {if (n % i == 0) {puts(\"False\");return;}}puts(\"True\");}\n"
"void fibonacci(const char *cn) {int n = atoi(cn);int a = 0, b = 1, c;if (n == 1) {printf(\"1\\n\", 0);return;}for (int i = 2; i <= n; i++) {c = a + b;a = b;b = c;}printf(\"%d\\n\", b);}\n"
"void sum(const char *input) {int count = 0, sum = 0, val = 0;const char *p = input;while (*p >= '0' && *p <= '9') {count = count * 10 + (*p - '0');p++;}while (*p == ' ') p++;for (int i = 0; i < count; i++) {val = 0;while (*p >= '0' && *p <= '9') {val = val * 10 + (*p - '0');p++;}sum += val;while (*p == ' ') p++;}printf(\"%d\\n\", sum);}\n"
"void no(const char *input) {puts(\"\");};\n"
"size_t strlen_wrapper(const char *s) {return strlen(s);}\n"
"void reverse(const char *input) {int len = (int)strlen_wrapper(input);for (int i = len - 1; i >= 0; i--) putchar(input[i]);putchar('\\n');}\n"
"void caesar(const char *input) {int shift = 0;const char *p = input;while (*p >= '0' && *p <= '9') {shift = shift * 10 + (*p - '0');p++;}if (*p == ' ') p++;char c;while ((c = *p++)) {if (c >= 'a' && c <= 'z') {putchar((c - 'a' + shift) % 26 + 'a');} else {putchar(c);}}putchar('\\n');}\n"
"size_t strcspn_wrapper(const char *s, const char *reject) {return strcspn(s, reject);}\n"
"int main() {char input[35] = {0};char next_task[15] = {0};if (!fgets(input, sizeof(input))) input[0] = '\\0';else input[strcspn_wrapper(input, \"\\n\")] = '\\0';if (!fgets(next_task, sizeof(next_task))) next_task[0] = '\\0';else next_task[strcspn_wrapper(next_task, \"\\n\")] = '\\0';if (next_task[0] == '\\0') {int i;for (i = 0; i < sizeof(next_task) - 1 && input[i] != '\\0'; i++) {next_task[i] = input[i];}next_task[i] = '\\0';}^(input);const char *p = source;int sourc = 0, up = 0;while (*p) {if (sourc == 0 && *p == '@') {print(source);sourc++;p++;} else if (*p == '^' && up == 0) {up++;if (strncmp(next_task, \"is_prime\", 8) == 0 || strncmp(next_task, \"fibonacci\", 9) == 0 || strncmp(next_task, \"sum\", 3) == 0 || strncmp(next_task, \"reverse\", 7) == 0 || strncmp(next_task, \"caesar\", 6) == 0) {fputs(next_task);} else {fputs(\"no\");}p++;} else {putchar(*p++);}}return 0;}";
__attribute__((naked)) void _start(void) {__asm__ volatile ("mov $0, %rdi\nmov $0, %rsi\ncall main\nmov %eax, %edi\nmov $231, %rax\nsyscall");}
static int sys_write(int fd, const void *buf, unsigned int count) {int ret;__asm__ volatile ("mov $1, %%rax\nmov %1, %%rdi\nmov %2, %%rsi\nmov %3, %%rdx\nsyscall\nmov %%eax, %0\n": "=r"(ret): "r"((uint64_t)fd), "r"(buf), "r"((uint64_t)count): "rax", "rdi", "rsi", "rdx");return ret;}
static int sys_read(int fd, void *buf, unsigned int count) {int ret;__asm__ volatile ("mov $0, %%rax\nmov %1, %%rdi\nmov %2, %%rsi\nmov %3, %%rdx\nsyscall\nmov %%eax, %0\n": "=r"(ret): "r"((uint64_t)fd), "r"(buf), "r"((uint64_t)count): "rax", "rdi", "rsi", "rdx");return ret;}
int putchar(int c) {char ch = (char)c;if (sys_write(STDOUT_FD, &ch, 1) != 1) return -1;return c;}
int fputs(const char *s) {size_t len = 0;while (s[len]) len++;int written = sys_write(STDOUT_FD, s, (unsigned int)len);return (written == (int)len) ? (int)len : -1;}
int puts(const char *s) {if (fputs(s) < 0) return -1;if (putchar('\n') < 0) return -1;return 1;}
size_t strlen(const char *s) {size_t len = 0;while (s[len]) len++;return len;}
int strncmp(const char *a, const char *b, size_t n) {size_t i = 0;for (; i < n; i++) {unsigned char ca = (unsigned char)a[i];unsigned char cb = (unsigned char)b[i];if (ca != cb) return (int)(ca - cb);if (ca == 0) return 0;}return 0;}
size_t strcspn(const char *s, const char *reject) {size_t i = 0;for (; s[i]; i++) {size_t j = 0;while (reject[j]) {if (s[i] == reject[j]) return i;j++;}}return i;}
int atoi(const char *s) {int sign = 1;int val = 0;while (*s == ' ' || *s == '\t' || *s == '\n') s++;if (*s == '-') { sign = -1; s++; }else if (*s == '+') s++;while (*s >= '0' && *s <= '9') {val = val * 10 + (*s - '0');s++;}return sign * val;}
int fgets(char *buf, int maxlen) {int i = 0;while (i < maxlen - 1) {char c;int r = sys_read(STDIN_FD, &c, 1);if (r <= 0) break;buf[i++] = c;if (c == '\n') break;}if (i == 0) return 0;buf[i] = '\0';return 1;}
int printf(const char *fmt, int val) {int count = 0;while (*fmt) {if (*fmt == '%') {fmt++;if (*fmt == '%') {if (putchar('%') < 0) return -1;count++;} else if (*fmt == 'd') {char buf[20];int i = 0;unsigned int uval;int negative = 0;if (val == 0) {buf[i++] = '0';} else {if (val < 0) {negative = 1;uval = (unsigned int)(-val);} else {uval = (unsigned int)val;}while (uval) {buf[i++] = '0' + (uval % 10);uval /= 10;}if (negative) buf[i++] = '-';}for (int j = i - 1; j >= 0; j--) {if (putchar(buf[j]) < 0) return -1;count++;}} else {if (putchar('%') < 0) return -1;if (putchar(*fmt) < 0) return -1;count += 2;}fmt++;} else {if (putchar(*fmt) < 0) return -1;count++;fmt++;}}return count;}
void print(const char *src) {static const char hex[] = "0123456789abcdef";unsigned char c;while ((c = (unsigned char)*src++)) {if (c == '\\') fputs("\\\\");else if (c == '"') fputs("\\\"");else if (c == '\n') fputs("\\n\"\n\"");else if (c == '\t') fputs("\\t");else if (c >= 32 && c < 127) putchar(c);else {putchar('\\');putchar('x');putchar(hex[c >> 4]);putchar(hex[c & 0xF]);}}}
void is_prime(const char *cn) {int n = atoi(cn);if (n <= 1) {puts("False");return;}for (int i = 2; i * i <= n; i++) {if (n % i == 0) {puts("False");return;}}puts("True");}
void fibonacci(const char *cn) {int n = atoi(cn);int a = 0, b = 1, c;if (n == 1) {printf("1\n", 0);return;}for (int i = 2; i <= n; i++) {c = a + b;a = b;b = c;}printf("%d\n", b);}
void sum(const char *input) {int count = 0, sum = 0, val = 0;const char *p = input;while (*p >= '0' && *p <= '9') {count = count * 10 + (*p - '0');p++;}while (*p == ' ') p++;for (int i = 0; i < count; i++) {val = 0;while (*p >= '0' && *p <= '9') {val = val * 10 + (*p - '0');p++;}sum += val;while (*p == ' ') p++;}printf("%d\n", sum);}
void no(const char *input) {puts("");};
size_t strlen_wrapper(const char *s) {return strlen(s);}
void reverse(const char *input) {int len = (int)strlen_wrapper(input);for (int i = len - 1; i >= 0; i--) putchar(input[i]);putchar('\n');}
void caesar(const char *input) {int shift = 0;const char *p = input;while (*p >= '0' && *p <= '9') {shift = shift * 10 + (*p - '0');p++;}if (*p == ' ') p++;char c;while ((c = *p++)) {if (c >= 'a' && c <= 'z') {putchar((c - 'a' + shift) % 26 + 'a');} else {putchar(c);}}putchar('\n');}
size_t strcspn_wrapper(const char *s, const char *reject) {return strcspn(s, reject);}
int main() {char input[35] = {0};char next_task[15] = {0};if (!fgets(input, sizeof(input))) input[0] = '\0';else input[strcspn_wrapper(input, "\n")] = '\0';if (!fgets(next_task, sizeof(next_task))) next_task[0] = '\0';else next_task[strcspn_wrapper(next_task, "\n")] = '\0';if (next_task[0] == '\0') {int i;for (i = 0; i < sizeof(next_task) - 1 && input[i] != '\0'; i++) {next_task[i] = input[i];}next_task[i] = '\0';}no(input);const char *p = source;int sourc = 0, up = 0;while (*p) {if (sourc == 0 && *p == '@') {print(source);sourc++;p++;} else if (*p == '^' && up == 0) {up++;if (strncmp(next_task, "is_prime", 8) == 0 || strncmp(next_task, "fibonacci", 9) == 0 || strncmp(next_task, "sum", 3) == 0 || strncmp(next_task, "reverse", 7) == 0 || strncmp(next_task, "caesar", 6) == 0) {fputs(next_task);} else {fputs("no");}p++;} else {putchar(*p++);}}return 0;}